=== Nike073i/MiACD/Laboratory 1-3/car_park.dtd
<!ELEMENT park (car*)>
        <!ELEMENT car (brand,model,year,mileage)>
        <!ATTLIST car id ID #REQUIRED>
        <!ELEMENT brand (#PCDATA)>
        <!ELEMENT model (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT mileage (#PCDATA)>

=== Nike073i/MiACD/Laboratory 1-3/car_park.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="car_park.xsl"?>
<!DOCTYPE park SYSTEM "car_park.dtd">
<park>
    <car id="firstCar">
        <brand>Lada</brand>
        <model>Калина</model>
        <year>2013</year>
        <mileage>116300</mileage>
    </car>
    <car id="secondCar">
       <brand>Volkswagen</brand>
       <model>Polo</model>
       <year>2016</year>
       <mileage>63560</mileage>
   </car>
   <car id="thirdCar">
       <brand>Honda</brand>
       <model>Accord</model>
       <year>2011</year>
       <mileage>175000</mileage>
   </car>
</park>
