=== Nike073i/MiACD/Laboratory 5-6/cars.xsd
<?xml version="1.0"?>
<xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name="INTEGER">
        <xsd:restriction base="xsd:int">
            <xsd:maxInclusive value="2147483647"/>
            <xsd:minInclusive value="-2147483648"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="VARCHAR">
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="RowType.Miacd.public.car">
        <xsd:sequence>
            <xsd:element name="brand" type="VARCHAR" nillable="false"></xsd:element>
            <xsd:element name="model" type="VARCHAR" nillable="false"></xsd:element>
            <xsd:element name="production_year" type="INTEGER" nillable="false"></xsd:element>
            <xsd:element name="mileage" type="INTEGER" nillable="false"></xsd:element>
            <xsd:element name="vin_num" type="VARCHAR" nillable="false"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="INTEGER" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="cars">
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="car" type="RowType.Miacd.public.car"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="cars" type="cars"></xsd:element>
</xsd:schema>

=== Nike073i/MiACD/Laboratory 5-6/cars.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cars.xsl"?>
<cars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cars.xsd">
    <car id="1">
        <brand>Lada</brand>
        <model>Калина 2</model>
        <production_year>2013</production_year>
        <mileage>116300</mileage>
        <vin_num>XTA219210D0020265</vin_num>
    </car>

    <car id="2">
        <brand>Volkswagen</brand>
        <model>Polo</model>
        <production_year>2013</production_year>
        <mileage>116300</mileage>
        <vin_num>XBA649532D1W172W5</vin_num>
    </car>

    <car id="3">
        <brand>Honda</brand>
        <model>Accord</model>
        <production_year>2011</production_year>
        <mileage>178230</mileage>
        <vin_num>1HB139417D6TSS0XB</vin_num>
    </car>
</cars>
