=== Nike073i/MiACD/Laboratory 5-6/drivers.xsd
<xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name="INTEGER">
        <xsd:restriction base="xsd:int">
            <xsd:maxInclusive value="2147483647"/>
            <xsd:minInclusive value="-2147483648"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="VARCHAR">
        <xsd:restriction base="xsd:string">
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="RowType.Miacd.public.driver">
        <xsd:sequence>
            <xsd:element name="first_name" type="VARCHAR" nillable="false"></xsd:element>
            <xsd:element name="second_name" type="VARCHAR" nillable="false"></xsd:element>
            <xsd:element name="contact_num" type="VARCHAR" nillable="false"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="INTEGER" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="drivers">
        <xsd:sequence minOccurs="1" maxOccurs="unbounded">
            <xsd:element name="driver" type="RowType.Miacd.public.driver"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="drivers" type="drivers"/>

</xsd:schema>

=== Nike073i/MiACD/Laboratory 5-6/drivers.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="drivers.xsl"?>
<drivers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="drivers.xsd">
    <driver id="1001">
        <first_name>Иван</first_name>
        <second_name>Иванов</second_name>
        <contact_num>+79156346230</contact_num>
    </driver>

    <driver id="1002">
        <first_name>Петр</first_name>
        <second_name>Ломов</second_name>
        <contact_num>+79271135190</contact_num>
    </driver>

    <driver id="1003">
        <first_name>Николай</first_name>
        <second_name>Сергеев</second_name>
        <contact_num>+79631101115</contact_num>
    </driver>
</drivers>
